### ISSUE TITLE
Feature request: Tabbing

### ISSUE THREAD

**Issue by nodgear** [LGUG2Z/yatta#10]
**Feature:** Window tabs

**How it's supposed to behave:** Window tabs allows stacks of windows, similar to how a browser tab works, the active tab(window) is the topmost and visible one.
That would allow for awesome workflow and less cramped windows.

[Here's stackline from yabai](https://github.com/AdamWagner/stackline), as reference.

**Comment by LGUG2Z** [comment]
This would be a great feature. I don't think I'm going to have time to start working on this in the short term, but I'm happy to review and consider implementation proposals if anyone would like to take a stab at it in the meanwhile.

**Comment by LGUG2Z** [comment]
@nodgear Please check out https://github.com/LGUG2Z/komorebi which has support for window stacks 🎉
