### ISSUE TITLE
Building Error

### ISSUE THREAD

**Issue by kokopi-dev** [LGUG2Z/yatta#13]
Is it possible to compile this on WSL? I'm using ubuntu 18.04 and followed the rust setup instructions for WSL.
After setting up it gives me this toolchain: `stable-x86_64-unknown-linux-gnu`.

I'm getting an error when trying to run `cargo install --path yatta`, here is the verbose message:

![image](https://user-images.githubusercontent.com/39069737/120094109-4731a380-c0d3-11eb-99df-e39e287f40a5.png)

I have never touched rust before, so I'm not sure if I'm missing a different toolchain or something.

**Comment by LGUG2Z** [comment]
Hello! `yatta` and `yattac` must both be compiled on Windows directly, not on WSL.

You will need to install the stable Rust toolchain on Windows with [rustup](https://rustup.rs/) (I am using the `x86_64-pc-windows-msvc` toolchain specifically for `yatta` development) and also the [Build Tools for Visual Studio 2019](https://stackoverflow.com/a/55603112).

Once that is all set up you should just be able to open a Powershell terminal, clone the repo and run the `cargo install` commands again.

**Comment by kokopi-dev** [comment]
Can confirm that it works with `x86_64-pc-windows-msvc` toolchain. Thanks.
