### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by ghost** [LGUG2Z/yatta#16]
Because this project has no license, forking and modifying it or using the source code even for just a pull request is illegal. I already made a [pull request](https://github.com/LGUG2Z/yatta/pull/15) before noticing this which technically violates your copyright, so if you want me to I can delete my fork and pull request.

**Comment by LGUG2Z** [comment]
Thank you for raising this! I will do a bit more reading and see which licenses other tiling window managers are using and make a decision on licensing by this weekend.

Please keep open the PR, you have the honour of being the first user to contribute significant code to a feature on `yatta` and I am extremely grateful for the time and effort that you have put in to understanding the codebase and working on the implementation of a significant, non-trivial feature!

**Comment by LGUG2Z** [comment]
After looking into this over the past week, I have decided to go with the MIT license for this project. I will make the relevant updates on the `master` branch soon.

**Comment by LGUG2Z** [comment]
Closed by https://github.com/LGUG2Z/yatta/commit/04ff5e2f94fcba82756b1ed19de3739d7286156e
