### ISSUE TITLE
Feature request: Multi-monitor support

### ISSUE THREAD

**Issue by eramdam** [LGUG2Z/yatta#2]
What the title says 😅 

If it's already there, I couldn't find any command to handle that. Very promising project already, as a fan of yabai on macOS I'm very happy to see a (good) equivalent shaping up on Windows 🙇‍♂️ 🙏

**Comment by LGUG2Z** [comment]
Unfortunately I have only ever really used a single monitor so I'm not sure what the desired behaviours should be here.

Can you share a checklist of desired behaviours when working with Yatta across multiple monitors and an explanation of what happens instead of those desired behaviours currently? I think we can start working on a solution from there. I imagine most of the changes will probably need to be made somewhere around here: https://github.com/LGUG2Z/yatta/blob/master/yatta/src/desktop.rs#L32

**Comment by eramdam** [comment]
> Unfortunately I have only ever really used a single monitor so I'm not sure what the desired behaviours should be here.
> 
> Can you share a checklist of desired behaviours when working with Yatta across multiple monitors and an explanation of what happens instead of those desired behaviours currently? I think we can start working on a solution from there. I imagine most of the changes will probably need to be made somewhere around here: https://github.com/LGUG2Z/yatta/blob/master/yatta/src/desktop.rs#L32

I guess at the very least it would need:
- be able to tile windows on more than one display (right now if I have a window on my second monitor, yatta just tiles it with the others on the primary one)
- be able to move a given window to a specific display (yabai has `next`/`prev` shortcuts which I assume use the display index that macOS returns)
- be able to focus a given display

If that helps, here's what I have in my skhd config relative to displays

```
# Move to monitor
shift + ctrl + alt - left : yabai -m window --display prev; yabai -m display --focus prev
shift + ctrl + alt - right : yabai -m window --display next; yabai -m display --focus next
```

**Comment by LGUG2Z** [comment]
I have started work on some of the plumbing required for multi-monitor support on this branch: https://github.com/LGUG2Z/yatta/tree/feature/multiple-monitors

I'll ping you on this thread when I have a build that I believe allows for tiling across multiple monitors, and once you can confirm the behaviour of that, I will turn my attention to moving windows across monitors and focusing across monitors.

**Comment by LGUG2Z** [comment]
@eramdam Cross your fingers and try installing `yatta` from this commit https://github.com/LGUG2Z/yatta/commit/104a1aeed578071c8d24496583bdb227e2db8de4

**Comment by LGUG2Z** [comment]
@eramdam https://github.com/LGUG2Z/yatta/commit/ad2833d69f1d6893f14a070693c5d567288adb1c this commit also exposes the following commands via `yattac` to move windows between displays and change focus between displays.

```
yattac.exe move-to-display previous
yattac.exe move-to-display next
yattac.exe move-to-display-number 3
yattac.exe focus-display previous
yattac.exe focus-display next
yattac.exe focus-display-number 1
```

**Comment by eramdam** [comment]
It seems to work great as far as I can tell! I'm getting very close to a 1:1 feature match with yabai now! I'm just missing a[ "warp" command](https://github.com/eramdam/dotfiles/blob/037167e43db5ea2a1de113e37734a07349bfccf8/conf/.skhdrc#L42-L46) (basically move but creates a new tile in the destination afaict) now, but maybe im missing something in the existing commands

**Comment by eramdam** [comment]
Oh and also, is there supposed to be a way to resize windows? Or at least make it so manually resizing windows makes yatta aware of the new size? (Feel free to tell me to open another issue because i guess I'm getting off-topic 😁 )
