### ISSUE TITLE
Tree operations

### ISSUE THREAD

**Issue by LGUG2Z** [LGUG2Z/yatta#4]
It seems to work great as far as I can tell! I'm getting very close to a 1:1 feature match with yabai now! I'm just missing a[ "warp" command](https://github.com/eramdam/dotfiles/blob/037167e43db5ea2a1de113e37734a07349bfccf8/conf/.skhdrc#L42-L46) (basically move but creates a new tile in the destination afaict) now, but maybe im missing something in the existing commands

_Originally posted by @eramdam in https://github.com/LGUG2Z/yatta/issues/2#issuecomment-803249537_

**Comment by nodgear** [comment]
1:1 with yabai? nice one.
I miss the stackline, being able to stack windows is swap between then is great!
